### ISSUE TITLE
Client crash.

### ISSUE THREAD

**Issue by netcore10** [Snownee/Loquat#1]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

1.0.0

### Modloader version

fabric loader 14.21 api 0.76

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://paste.atlauncher.com/view/2db4323d-3432-4dfe-9744-0374ab212092

**Comment by Snownee** [comment]
Hello, you can install Lychee as a workaround
